/*Generated by xorm v0.7.0.0504 2019-06-25 16:48:14, from mysql to MYSQL*/

CREATE TABLE IF NOT EXISTS `t_person` (
  `f_age` INT(11) NULL,
  `f_id` INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `f_name` VARCHAR(30) NOT NULL,
  `f_sex` VARCHAR(2) NULL
  ) ENGINE=InnoDB;

